[2025-06-22T15:56:09.426+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T15:56:09.445+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: start_kafka_hadoop_and_run_notebooks.start_yarn manual__2025-06-22T08:46:29.704023+00:00 [queued]>
[2025-06-22T15:56:09.451+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: start_kafka_hadoop_and_run_notebooks.start_yarn manual__2025-06-22T08:46:29.704023+00:00 [queued]>
[2025-06-22T15:56:09.451+0700] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2025-06-22T15:56:09.465+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_yarn> on 2025-06-22 08:46:29.704023+00:00
[2025-06-22T15:56:09.471+0700] {standard_task_runner.py:63} INFO - Started process 56618 to run task
[2025-06-22T15:56:09.475+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'start_kafka_hadoop_and_run_notebooks', 'start_yarn', 'manual__2025-06-22T08:46:29.704023+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/start_DAG.py', '--cfg-path', '/tmp/tmpq450uic2']
[2025-06-22T15:56:09.476+0700] {standard_task_runner.py:91} INFO - Job 21: Subtask start_yarn
[2025-06-22T15:56:09.516+0700] {task_command.py:426} INFO - Running <TaskInstance: start_kafka_hadoop_and_run_notebooks.start_yarn manual__2025-06-22T08:46:29.704023+00:00 [running]> on host Panda
[2025-06-22T15:56:09.576+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='group_03' AIRFLOW_CTX_DAG_ID='start_kafka_hadoop_and_run_notebooks' AIRFLOW_CTX_TASK_ID='start_yarn' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T08:46:29.704023+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-22T08:46:29.704023+00:00'
[2025-06-22T15:56:09.577+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-22T15:56:09.578+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-22T15:56:09.578+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "'start-yarn.sh'"]
[2025-06-22T15:56:09.590+0700] {subprocess.py:86} INFO - Output:
[2025-06-22T15:56:10.429+0700] {subprocess.py:93} INFO - Starting resourcemanager
[2025-06-22T15:56:10.523+0700] {subprocess.py:93} INFO - resourcemanager is running as process 42892.  Stop it first and ensure /tmp/hadoop-panda-resourcemanager.pid file is empty before retry.
[2025-06-22T15:56:10.524+0700] {subprocess.py:93} INFO - Starting nodemanagers
[2025-06-22T15:56:10.968+0700] {subprocess.py:93} INFO - localhost: nodemanager is running as process 43058.  Stop it first and ensure /tmp/hadoop-panda-nodemanager.pid file is empty before retry.
[2025-06-22T15:56:11.708+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-22T15:56:11.709+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-22T15:56:11.716+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-22T15:56:11.718+0700] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=start_kafka_hadoop_and_run_notebooks, task_id=start_yarn, execution_date=20250622T084629, start_date=20250622T085609, end_date=20250622T085611
[2025-06-22T15:56:11.733+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task start_yarn (Bash command failed. The command returned a non-zero exit code 1.; 56618)
[2025-06-22T15:56:11.773+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-22T15:56:11.788+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T15:56:11.789+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
