[2025-06-22T14:53:49.223+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T14:53:49.235+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: start_kafka_hadoop_and_run_notebooks.start_hdfs manual__2025-06-22T07:47:39.266622+00:00 [queued]>
[2025-06-22T14:53:49.238+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: start_kafka_hadoop_and_run_notebooks.start_hdfs manual__2025-06-22T07:47:39.266622+00:00 [queued]>
[2025-06-22T14:53:49.238+0700] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2025-06-22T14:53:49.252+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_hdfs> on 2025-06-22 07:47:39.266622+00:00
[2025-06-22T14:53:49.259+0700] {standard_task_runner.py:63} INFO - Started process 28877 to run task
[2025-06-22T14:53:49.263+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'start_kafka_hadoop_and_run_notebooks', 'start_hdfs', 'manual__2025-06-22T07:47:39.266622+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/start_DAG.py', '--cfg-path', '/tmp/tmpxsdlmhqd']
[2025-06-22T14:53:49.264+0700] {standard_task_runner.py:91} INFO - Job 6: Subtask start_hdfs
[2025-06-22T14:53:49.313+0700] {task_command.py:426} INFO - Running <TaskInstance: start_kafka_hadoop_and_run_notebooks.start_hdfs manual__2025-06-22T07:47:39.266622+00:00 [running]> on host Panda
[2025-06-22T14:53:49.346+0700] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'start_hdfs', field 'bash_command'. Template: 'start-dfs.sh'
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: start-dfs.sh
[2025-06-22T14:53:49.347+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2476, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2629, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3079, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1336, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: start-dfs.sh
[2025-06-22T14:53:49.350+0700] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=start_kafka_hadoop_and_run_notebooks, task_id=start_hdfs, execution_date=20250622T074739, start_date=20250622T075349, end_date=20250622T075349
[2025-06-22T14:53:49.359+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task start_hdfs (start-dfs.sh; 28877)
[2025-06-22T14:53:49.394+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-22T14:53:49.415+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T14:53:49.425+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
