[2025-06-26T18:23:10.721+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-26T18:23:10.752+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: send_data_to_powerbi.send_to_power_bi scheduled__2025-06-26T11:10:00+00:00 [queued]>
[2025-06-26T18:23:10.760+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: send_data_to_powerbi.send_to_power_bi scheduled__2025-06-26T11:10:00+00:00 [queued]>
[2025-06-26T18:23:10.760+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2025-06-26T18:23:10.780+0700] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): send_to_power_bi> on 2025-06-26 11:10:00+00:00
[2025-06-26T18:23:10.787+0700] {standard_task_runner.py:63} INFO - Started process 9462 to run task
[2025-06-26T18:23:10.791+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'send_data_to_powerbi', 'send_to_power_bi', 'scheduled__2025-06-26T11:10:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/load_power_bi.py', '--cfg-path', '/tmp/tmpebyrkbyc']
[2025-06-26T18:23:10.792+0700] {standard_task_runner.py:91} INFO - Job 50: Subtask send_to_power_bi
[2025-06-26T18:23:10.835+0700] {task_command.py:426} INFO - Running <TaskInstance: send_data_to_powerbi.send_to_power_bi scheduled__2025-06-26T11:10:00+00:00 [running]> on host Panda
[2025-06-26T18:23:10.897+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='group_03' AIRFLOW_CTX_DAG_ID='send_data_to_powerbi' AIRFLOW_CTX_TASK_ID='send_to_power_bi' AIRFLOW_CTX_EXECUTION_DATE='2025-06-26T11:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-26T11:10:00+00:00'
[2025-06-26T18:23:10.898+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-26T18:23:10.904+0700] {client.py:1116} INFO - Listing '/transactions_by_hour_compacted/'.
[2025-06-26T18:23:10.930+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-26T18:23:10.931+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/panda/Documents/ODAP/Project/airflow/dags/load_power_bi.py", line 43, in send_new_data
    files = HDFS_CLIENT.list(FOLDER_HDFS_PATH)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/hdfs/client.py", line 1118, in list
    statuses = self._list_status(hdfs_path).json()['FileStatuses']['FileStatus']
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/hdfs/client.py", line 118, in api_handler
    raise err
hdfs.util.HdfsError: File /transactions_by_hour_compacted does not exist.
[2025-06-26T18:23:10.937+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=send_data_to_powerbi, task_id=send_to_power_bi, execution_date=20250626T111000, start_date=20250626T112310, end_date=20250626T112310
[2025-06-26T18:23:10.949+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 50 for task send_to_power_bi (File /transactions_by_hour_compacted does not exist.; 9462)
[2025-06-26T18:23:10.962+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-26T18:23:10.979+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-26T18:23:10.980+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
