[2025-06-22T16:18:05.515+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T16:18:05.535+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: start_kafka_hadoop_and_run_notebooks.run_kafka_notebook manual__2025-06-22T09:11:53.271575+00:00 [queued]>
[2025-06-22T16:18:05.540+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: start_kafka_hadoop_and_run_notebooks.run_kafka_notebook manual__2025-06-22T09:11:53.271575+00:00 [queued]>
[2025-06-22T16:18:05.540+0700] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2025-06-22T16:18:05.561+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_kafka_notebook> on 2025-06-22 09:11:53.271575+00:00
[2025-06-22T16:18:05.566+0700] {standard_task_runner.py:63} INFO - Started process 12744 to run task
[2025-06-22T16:18:05.571+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'start_kafka_hadoop_and_run_notebooks', 'run_kafka_notebook', 'manual__2025-06-22T09:11:53.271575+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/start_DAG.py', '--cfg-path', '/tmp/tmpxhftt1oe']
[2025-06-22T16:18:05.571+0700] {standard_task_runner.py:91} INFO - Job 33: Subtask run_kafka_notebook
[2025-06-22T16:18:05.611+0700] {task_command.py:426} INFO - Running <TaskInstance: start_kafka_hadoop_and_run_notebooks.run_kafka_notebook manual__2025-06-22T09:11:53.271575+00:00 [running]> on host Panda
[2025-06-22T16:18:05.676+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='group_03' AIRFLOW_CTX_DAG_ID='start_kafka_hadoop_and_run_notebooks' AIRFLOW_CTX_TASK_ID='run_kafka_notebook' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T09:11:53.271575+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-22T09:11:53.271575+00:00'
[2025-06-22T16:18:05.677+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-22T16:18:05.678+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-22T16:18:05.679+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        source /home/panda/Documents/ODAP/Project/venv310/bin/activate &&         jupyter nbconvert --to notebook --execute /home/panda/Documents/ODAP/Project/kafka/producer.ipynb --output /tmp/output_kafka.ipynb \n        ']
[2025-06-22T16:18:05.691+0700] {subprocess.py:86} INFO - Output:
[2025-06-22T16:18:05.783+0700] {subprocess.py:93} INFO - usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
[2025-06-22T16:18:05.783+0700] {subprocess.py:93} INFO -                [--paths] [--json] [--debug]
[2025-06-22T16:18:05.784+0700] {subprocess.py:93} INFO -                [subcommand]
[2025-06-22T16:18:05.784+0700] {subprocess.py:93} INFO - 
[2025-06-22T16:18:05.784+0700] {subprocess.py:93} INFO - Jupyter: Interactive Computing
[2025-06-22T16:18:05.784+0700] {subprocess.py:93} INFO - 
[2025-06-22T16:18:05.784+0700] {subprocess.py:93} INFO - positional arguments:
[2025-06-22T16:18:05.785+0700] {subprocess.py:93} INFO -   subcommand     the subcommand to launch
[2025-06-22T16:18:05.785+0700] {subprocess.py:93} INFO - 
[2025-06-22T16:18:05.785+0700] {subprocess.py:93} INFO - options:
[2025-06-22T16:18:05.785+0700] {subprocess.py:93} INFO -   -h, --help     show this help message and exit
[2025-06-22T16:18:05.785+0700] {subprocess.py:93} INFO -   --version      show the versions of core jupyter packages and exit
[2025-06-22T16:18:05.785+0700] {subprocess.py:93} INFO -   --config-dir   show Jupyter config dir
[2025-06-22T16:18:05.786+0700] {subprocess.py:93} INFO -   --data-dir     show Jupyter data dir
[2025-06-22T16:18:05.786+0700] {subprocess.py:93} INFO -   --runtime-dir  show Jupyter runtime dir
[2025-06-22T16:18:05.786+0700] {subprocess.py:93} INFO -   --paths        show all Jupyter paths. Add --json for machine-readable
[2025-06-22T16:18:05.786+0700] {subprocess.py:93} INFO -                  format.
[2025-06-22T16:18:05.786+0700] {subprocess.py:93} INFO -   --json         output paths as machine-readable json
[2025-06-22T16:18:05.786+0700] {subprocess.py:93} INFO -   --debug        output debug information about paths
[2025-06-22T16:18:05.786+0700] {subprocess.py:93} INFO - 
[2025-06-22T16:18:05.787+0700] {subprocess.py:93} INFO - Available subcommands: kernel kernelspec migrate run troubleshoot
[2025-06-22T16:18:05.787+0700] {subprocess.py:93} INFO - 
[2025-06-22T16:18:05.787+0700] {subprocess.py:93} INFO - Jupyter command `jupyter-nbconvert` not found.
[2025-06-22T16:18:05.795+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-22T16:18:05.795+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-22T16:18:05.804+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-22T16:18:05.807+0700] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=start_kafka_hadoop_and_run_notebooks, task_id=run_kafka_notebook, execution_date=20250622T091153, start_date=20250622T091805, end_date=20250622T091805
[2025-06-22T16:18:05.822+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 33 for task run_kafka_notebook (Bash command failed. The command returned a non-zero exit code 1.; 12744)
[2025-06-22T16:18:05.861+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-22T16:18:05.875+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T16:18:05.876+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
