[2025-06-22T15:54:16.758+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T15:54:16.778+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: start_kafka_hadoop_and_run_notebooks.start_yarn manual__2025-06-22T08:46:35.834149+00:00 [queued]>
[2025-06-22T15:54:16.783+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: start_kafka_hadoop_and_run_notebooks.start_yarn manual__2025-06-22T08:46:35.834149+00:00 [queued]>
[2025-06-22T15:54:16.784+0700] {taskinstance.py:2303} INFO - Starting attempt 3 of 4
[2025-06-22T15:54:16.798+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_yarn> on 2025-06-22 08:46:35.834149+00:00
[2025-06-22T15:54:16.803+0700] {standard_task_runner.py:63} INFO - Started process 56077 to run task
[2025-06-22T15:54:16.807+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'start_kafka_hadoop_and_run_notebooks', 'start_yarn', 'manual__2025-06-22T08:46:35.834149+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/start_DAG.py', '--cfg-path', '/tmp/tmp6q6pyrlb']
[2025-06-22T15:54:16.808+0700] {standard_task_runner.py:91} INFO - Job 20: Subtask start_yarn
[2025-06-22T15:54:16.852+0700] {task_command.py:426} INFO - Running <TaskInstance: start_kafka_hadoop_and_run_notebooks.start_yarn manual__2025-06-22T08:46:35.834149+00:00 [running]> on host Panda
[2025-06-22T15:54:16.910+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='group_03' AIRFLOW_CTX_DAG_ID='start_kafka_hadoop_and_run_notebooks' AIRFLOW_CTX_TASK_ID='start_yarn' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T08:46:35.834149+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-22T08:46:35.834149+00:00'
[2025-06-22T15:54:16.911+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-22T15:54:16.912+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-22T15:54:16.913+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "'start-yarn.sh'"]
[2025-06-22T15:54:16.924+0700] {subprocess.py:86} INFO - Output:
[2025-06-22T15:54:17.735+0700] {subprocess.py:93} INFO - Starting resourcemanager
[2025-06-22T15:54:17.827+0700] {subprocess.py:93} INFO - resourcemanager is running as process 42892.  Stop it first and ensure /tmp/hadoop-panda-resourcemanager.pid file is empty before retry.
[2025-06-22T15:54:17.827+0700] {subprocess.py:93} INFO - Starting nodemanagers
[2025-06-22T15:54:18.288+0700] {subprocess.py:93} INFO - localhost: nodemanager is running as process 43058.  Stop it first and ensure /tmp/hadoop-panda-nodemanager.pid file is empty before retry.
[2025-06-22T15:54:19.046+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-22T15:54:19.047+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-22T15:54:19.056+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-22T15:54:19.059+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=start_kafka_hadoop_and_run_notebooks, task_id=start_yarn, execution_date=20250622T084635, start_date=20250622T085416, end_date=20250622T085419
[2025-06-22T15:54:19.073+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task start_yarn (Bash command failed. The command returned a non-zero exit code 1.; 56077)
[2025-06-22T15:54:19.105+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-22T15:54:19.120+0700] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-22T15:54:19.120+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
